#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpif90 int2d_strip.f90  -o int2d_strip.exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

