#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpif90 ABmul.f90  -o ABmul.exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

